---
#-------------------------------
# General Site Settings
baseurl: "" # The subpath of your site, e.g. /blog
url: "" # The base hostname & protocol for your site, e.g. http://example.com

title: Atom Technologies
logo: /assets/images/Logo60x60.png # You can add own logo
description: Atom Technologies is the publishing name for a small game creator who codes and designs fun games for Windows and Xbox devices.
copyright: 
# Preloader
preloader: true # To disable preloader change value to false

menu:
  - name: Home
    url: /
  - name: About
    url: /about/
  - name: Contact
    url: /contact/

# *** NOTE ***
# You can add submenus. For example:

#  menu:
#  - name: Home
#    url: /
#    submenu:
#     - name: Peru
#       url: /peru/
# ----------------------------------

layout_home_page: true # Homepage layout ( two layout is available, you can set the another layout by change the value of layout_home_page "true" to "false")

featured-post-slider: true # You can enable or disable the featured-post-slider using true or false values.

#-------------------------------
# Hero Section
hero:
  hero-subtitle: Atom Technologies is the publishing name for a small game creator who codes and designs fun games for Windows and Xbox devices.
  hero-banner: /assets/images/Logo.png # Add your banner image '/assets/images/'

#-------------------------------
# Author Settings
author:
  name: Atom Technologies
  bio: Atom Technologies is the publishing name for a small game creator who codes and designs fun games for Windows and Xbox devices.
  avatar: /assets/images/Logo60x60.png # Add your avatar 

#-------------------------------
# Contact Info
#contact:
#  email: atomtechnologies00@gmail.com
#  phone: +90 000 333 22
#  address:
#    city: Sydney
#    street: 6 rip carl Avenue CA 90733

# Contact Form
#contact-form: example@email.com

# Social links
social:
  - { icon: "ti-instagram", link: "https:/instagram.com/atom.technologies_"}
  - { icon: "ti-twitter-alt", link: "https://x.com/atomtechnologie" }
  - { icon: "ti-youtube", link: "https://youtube.com/@atom.technologies" }
  - { icon: "ti-pinterest-alt", link: "https://pin.it/1XUbAPDII" }

#-------------------------------
# Comment Section (Disqus)
disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Instagram Feed
instafeed: false # To enable the instafeed, use the value true. To turn off use the value false.
userID: 4044026246
accessToken: 4044026246.1677ed0.8896752506ed4402a0519d23b8f50a17

#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.

#-------------------------------
# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging
  - jekyll-archives

paginate: 10
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: "_pages"
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir: tag
tag_page_layout: tag_page
tag_permalink_style: pretty

# categories
jekyll-archives:
  enabled: all
  layout: category
  permalinks:
    category: "/category/:name/"

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
